### ISSUE TITLE
Add support for realloc()

### ISSUE THREAD

**Issue by spickartz** [jbreitbart/malloc_bt#1]
Applications using the realloc() function crash when preloading this library:

```
*** Error in `./memlab': realloc(): invalid pointer: 0x00000000021a0288 ***
```

```
#0  0x00007ffff721d5d7 in raise () from /lib64/libc.so.6
#1  0x00007ffff721ecc8 in abort () from /lib64/libc.so.6
#2  0x00007ffff725de07 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff7263c67 in malloc_printerr () from /lib64/libc.so.6
#4  0x00007ffff726894e in realloc () from /lib64/libc.so.6
#5  0x00007ffff725510b in getdelim () from /lib64/libc.so.6
#6  0x00007ffff77c8730 in numa_init () from /lib64/libnuma.so.1
#7  0x00007ffff7dea49f in _dl_init_internal () from /lib64/ld-linux-x86-64.so.2
#8  0x00007ffff7ddc45a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#9  0x0000000000000004 in ?? ()
#10 0x00007fffffffca41 in ?? ()
#11 0x00007fffffffca65 in ?? ()
#12 0x00007fffffffca68 in ?? ()
#13 0x00007fffffffca6d in ?? ()
#14 0x0000000000000000 in ?? ()
```

**Comment by jbreitbart** [comment]
Let me know if it is fixed for you, but my simple realloc test case works fine.
